--
CREATE DATABASE IF NOT EXISTS `db_sport` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `db_sport`;
-- --------------------------------------------------------

--
-- Structure de la table `etudiants`
--

CREATE TABLE IF NOT EXISTS `etudiants` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nom` varchar(20) NOT NULL,
  `prenom` varchar(20) NOT NULL,    
  `c1` smallint NOT NULL,
  `c2` smallint NOT NULL,  
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

--
-- Contenu de la table `candidats`
--
INSERT INTO `etudiants` (`id`, `nom`, `prenom`,`c1`, `c2`) VALUES
(1, 'Robbins', 'Willow',  1, 3),
(2, 'Whitney', 'Marshall', 4, 1),
(3, 'Mccormick', 'Cassidy',  4, 2),
(4, 'Curry', 'Keelie', 4, 3),
(5, 'Mercado', 'Wynne', 4, 1),
(6, 'Stewart', 'Claire',  5, 1),
(7, 'Nelson', 'Hilda', 5, 4),
(8, 'Sosa', 'Lenore',  2, 1),
(9, 'Leblanc', 'Lionel', 2, 5),
(10, 'Cummings', 'Joshua', 3, 5),
(11, 'Calderon', 'Jeanette', 4, 1),
(12, 'Clarke', 'Macy', 1, 5),
(13, 'Rodriguez', 'Orla',   3, 1),
(14, 'Terrell', 'August',   5, 4),
(15, 'Smith', 'Pearl',   1, 5),
(16, 'Romero', 'Andrew',   1, 3),
(17, 'Salazar', 'Ginger',   3, 4),
(18, 'Fernandez', 'Travis',   2, 1),
(19, 'Bentley', 'Zeph',   5, 2),
(20,  'Soto', 'Oleg',   3, 5),
(21, 'Jacobs', 'Ian',   1, 5),
(22, 'Williamson', 'Zenia',   4, 3),
(23, 'Dawson', 'Sloane',   5, 3),
(24, 'Robles', 'Randall',   4, 5),
(25, 'Koch', 'Aladdin',   4, 3),
(26, 'Reeves', 'Yoshio',   3, 4),
(27, 'Trujillo', 'Ignatius',   1, 2),
(28, 'Dudley', 'Shelly',   2, 1),
(29, 'Curtis', 'Wanda',   2, 4),
(30,  'Humphrey', 'Evan',   2, 1),
(31, 'Humphrey', 'Amela',   3, 2),
(32, 'Byers', 'Gavin',   3, 1),
(33, 'Sellers', 'Summer',   5, 3),
(34, 'Rojas', 'Jeanette',   1, 4),
(35, 'Schwartz', 'Xantha',   5, 3),
(36, 'Page', 'Dexter',   1, 2),
(37, 'Durham', 'Benjamin',   3, 5),
(38, 'Alvarez', 'Calvin',   4, 2),
(39, 'Banks', 'Cameron',   5, 2),
(40,  'Rivera', 'Uriel',   2, 4),
(41, 'Patel', 'Basil',   1, 4),
(42, 'Goodman', 'Murphy',   5, 4),
(43, 'Collins', 'Melyssa',   5, 3),
(44, 'Ratliff', 'Lavinia',   4, 5),
(45, 'Hartman', 'Rhea',   1, 2),
(46, 'Mcdonald', 'Honorato',   5, 3),
(47, 'Edwards', 'Perry',   5, 4),
(48, 'Reilly', 'Courtney',   2, 5),
(49, 'Shepard', 'Meredith',   2, 5),
(50,  'Witt', 'Rebekah',   1, 2),
(51, 'Maynard', 'Driscoll',   5, 3),
(52, 'Hicks', 'Brent',   2, 1),
(53, 'Woodard', 'Rashad',   3, 4),
(54, 'Velazquez', 'Hall',   1, 4),
(55, 'Rosa', 'Maile',   4, 2),
(56, 'Sellers', 'Martha',   4, 2),
(57, 'Schmidt', 'Roanna',   3, 1),
(58, 'Dixon', 'Thane',   4, 5),
(59, 'Daniels', 'Remedios',   3, 5),
(60,  'Aguilar', 'Madonna',   1, 5),
(61, 'Walker', 'Dale',   2, 1),
(62, 'Woods', 'Mannix',   4, 1),
(63, 'Burch', 'Erin',   1, 2),
(64, 'Hudson', 'Vivian',   1, 5),
(65, 'Alvarez', 'Ima',   3, 4),
(66, 'Barron', 'Yeo',   4, 5),
(67, 'May', 'Amos',   3, 5),
(68, 'Melton', 'Hedda',   3, 1),
(69, 'Santiago', 'Quon',   1, 5),
(70,  'David', 'Kibo',   3, 1),
(71, 'Colon', 'Wade',   5, 2),
(72, 'Travis', 'Cadman',   5, 4),
(73, 'Padilla', 'Hammett',   2, 4),
(74, 'Stark', 'Boris',   4, 1),
(75, 'Patton', 'Carl',   3, 5),
(76, 'Pope', 'Raphael',   1, 4),
(77, 'Flowers', 'Hashim',   3, 4),
(78, 'Valencia', 'Sylvester',   3, 2),
(79, 'Flynn', 'Samson',   3, 1),
(80,  'Vinson', 'Whilemina',   5, 2),
(81, 'Moody', 'Laurel',   2, 3),
(82, 'Wong', 'Inga',   3, 2),
(83, 'Kane', 'Samuel',   4, 5),
(84, 'Faulkner', 'Cecilia',   2, 4),
(85, 'Holder', 'Addison',   3, 4),
(86, 'Byers', 'Mikayla',   3, 5),
(87, 'Hendrix', 'Frances',   4, 3),
(88, 'George', 'Galena',   1, 4),
(89, 'Randolph', 'Carol',   2, 5),
(90,  'Parker', 'Allen',   5, 4);